name: Build Conda Distribution
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  unit_tests:
    name: build conda distribution
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10"]
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
      - name: Install conda dependencies
        run: |
          conda install conda-build
          conda install conda-verify
          conda install anaconda-client
      - name: Clone nlp-primitives feedstock
        run: |
          gh repo clone gsheni/nlp_primitives-feedstock
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_APPROVE_TOKEN }}
      - name: Run tests
        run: |
          cd nlp_primitives-feedstock
          git checkout add_tests
          python build-locally.py linux_python${{ matrix.python_version }}
