on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: Install Test
jobs:
  install_test:
    name: ${{ matrix.os }} - ${{ matrix.python_version }} install test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python_version: ["3.7", "3.8", "3.9", "3.10"]
        exclude:
          - python_version: "3.10"
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install requirements
        run: |
          pip config --site set global.progress_bar off
          pip install -r requirements.txt
          pip install -r complete-requirements.txt
          pip install -r test-requirements.txt
      - name: Create source distribution
        run: make package_nlp_primitives
      - name: Install source distribution
        run: |
          NLP_PRIMITIVES_VERSION=$(python setup.py --version)
          pip install dist/nlp_primitives-${NLP_PRIMITIVES_VERSION}.tar.gz
      - name: Run unit tests
        run: |
          cd nlp_primitives
          python -c "import nlp_primitives; print(nlp_primitives.__version__)"
          python -c "import sys; print(sys.path)"
          make -f ../Makefile unit-tests
