on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: Install Test
jobs:
  install_test:
    name: Install Test - ${{ matrix.os }} - ${{ matrix.python_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python_version: ["3.9", "3.10", "3.11"]
        exclude:
          - python_version: "3.10"
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Create source distribution
        run: make package
      - name: Install nlp_primtivies from sdist
        run: |
          python -m pip install unpacked_sdist/
      - name: Test by importing
        run: |
          python -c "import nlp_primitives; print(nlp_primitives.__version__)"
          python -c "import sys; print(sys.path)"
      - name: Check package conflicts
        run: |
          python -m pip check
