name: Latest Dependency Checker
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
    - name: Install pip and virtualenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install virtualenv
    - name: Update latest core dependencies
      run: |
        python -m virtualenv venv_core
        source venv_core/bin/activate
        make installdeps
        make checkdeps OUTPUT_FILEPATH=nlp_primitives/tests/requirement_files/latest_core_dependencies.txt
        cat nlp_primitives/tests/requirement_files/latest_core_dependencies.txt
    - name: Update latest complete dependencies
      run: |
        python -m virtualenv venv_complete
        source venv_complete/bin/activate
        make installdeps-test
        make checkdepscomplete OUTPUT_FILEPATH=nlp_primitives/tests/requirement_files/latest_complete_dependencies.txt
        cat nlp_primitives/tests/requirement_files/latest_complete_dependencies.txt
