on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: Lint Check
jobs:
  lint_tests:
    name: Lint Tests - Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.9"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install requirements
        run: |
          pip config --site set global.progress_bar off
          make installdeps-complete
          pip install -r test-requirements.txt
      - name: Run lint tests
        run: make lint-tests
