on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: Optional Primitive Test
jobs:
  optional_primitive_test:
    name: Python ${{ matrix.python_version }} - Featuretools ${{ matrix.featuretools_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "3.9", "3.10"]
        featuretools_version: ["Release", "Main"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install standard requirements
        run: |
          pip config --site set global.progress_bar off
          make installdeps
      - if: ${{ matrix.featuretools_version == 'Main' }}
        name: Install latest version of Featuretools from main branch
        run: pip install git+https://github.com/alteryx/featuretools.git@main#egg=featuretools --force-reinstall
      - name: Test optional primitives are not imported
        run: python -c "import nlp_primitives; assert all(p not in dir(nlp_primitives) for p in ('Elmo', 'UniversalSentenceEncoder'))"
      - name: Install complete requirements
        run: make installdeps-complete
      - if: ${{ matrix.featuretools_version == 'Main' }}
        name: Install latest version of Featuretools from main branch
        run: pip install git+https://github.com/alteryx/featuretools.git@main#egg=featuretools --force-reinstall
      - name: Test optional primitives are imported
        run: python -c "import nlp_primitives; assert all(p in dir(nlp_primitives) for p in ('Elmo', 'UniversalSentenceEncoder'))"
