on:
  schedule:
    # At 05:00 PM UTC
    - cron: "0 17 * * *"
  workflow_dispatch:
name: Scheduler
jobs:
  schedule_tests:
    name: Schedule Tests
    runs-on: ubuntu-latest
    steps:
      - name: Get workflow status from latest run
        uses: alteryx/gh-action-ci@v3
        id: is_workflow_success
        with:
          task: is_workflow_success
          repository: alteryx/nlp_primitives
          branch: main
          workflow: Unit Tests - Latest Dependencies
          token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Check for recent commit to Featuretools
        if: ${{ steps.is_workflow_success.outputs.value == 'True' }}
        uses: alteryx/gh-action-ci@v3
        id: is_recent_commit
        with:
          task: is_recent_commit
          repository: alteryx/featuretools
          recent: hours=25
          token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Run tests
        if: ${{ steps.is_recent_commit.outputs.value == 'True' }}
        uses: alteryx/gh-action-ci@v3
        with:
          task: run_workflow
          repository: alteryx/nlp_primitives
          branch: main
          workflow: unit_tests_with_latest_deps.yml
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
