name: Unit Tests - Minimum Dependencies
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  py37_unit_tests_minimum_dependencies:
    name: Unit Tests - 3.8 Minimum Dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        libraries: ["core", "complete"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Config pip, upgrade pip, and install graphviz
        run: |
          sudo apt update
          python -m pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          python -m pip install wheel
      - name: Install nlp-primitives with no dependencies
        run: |
          python -m pip install -e . --no-dependencies
      - name: Install nlp-primitives - minimum tests dependencies
        run: |
          python -m pip install -r nlp_primitives/tests/requirement_files/minimum_test_requirements.txt
      - if: ${{ matrix.libraries == 'core' }}
        name: Install nlp-primitives - minimum core dependencies
        run: |
          python -m pip install -r nlp_primitives/tests/requirement_files/minimum_core_requirements.txt
      - if: ${{ matrix.libraries == 'complete' }}
        name: Install nlp-primitives - minimum complete dependencies
        run: |
          python -m pip install -r nlp_primitives/tests/requirement_files/minimum_complete_requirements.txt
      - name: Run unit tests without code coverage
        run: |
          python -m pytest -x -n 2 featuretools/tests/
