on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

name: Unit Tests - Latest Dependencies
jobs:
  unit_tests:
    name: Unit Tests - ${{ matrix.os }} - Python ${{ matrix.python_version }} - Featuretools ${{ matrix.featuretools_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python_version: ["3.7", "3.8", "3.9"]
        featuretools_version: ["Release", "Main"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install requirements
        run: |
          pip config --site set global.progress_bar off
          make installdeps-complete
          pip install -r test-requirements.txt
      - if: ${{ matrix.featuretools_version == 'Main' }}
        name: Install latest version of Featuretools from main branch
        run: pip install git+https://github.com/alteryx/featuretools.git@main#egg=featuretools --force-reinstall
      - name: Run unit tests
        run: make unit-tests
